### ISSUE TITLE
In your demo, CoreFMDB.queue (FMDatabaseQueue) will block UI thread

### ISSUE THREAD

**Issue by elonchen** [nsdictionary/CoreFMDB#2]
你的框架能像CoreData一样不阻塞UI线程吗？

**Comment by CharlinFeng** [comment]
做了很多版本，这个版本阻塞UI线程是特别而为之的，

之前做的是基本多线程的。因为在后面会出现线程不能同步的问题，为了后面的一键ORM，所以做做了主线程CURD
